# CentOS 7 ami-29d1e34e
- name: Install
  hosts: production
  gather_facts: no
  vars:
  tasks:
    - raw: yum update -y
      become: yes

    - raw: yum upgrade -y
      become: yes

    - name: install packages
      yum: name={{item}} state=present update_cache=yes
      with_items:
        - gcc
        - make
        - ntp
        - wget
        - unzip
        - openssl
        - openssl-devel
        - pcre-devel
      become: yes

    - name: Japanese Time Setting
      command: "sh -c \"timedatectl set-timezone Asia/Tokyo\""
      become: yes

    - name: ntp setting
      copy: src=files/ntp.conf dest=/etc/ntp.conf
      become: yes

    - name: ntp restart
      service: name=ntpd state=restarted
      become: yes

    - name: history setting
      copy: src=files/profile.d/history.sh dest=/etc/profile.d/history.sh
      become: yes

    - name: init hosts
      copy: src=files/hosts dest=/etc/hosts
      become: yes

    - name: edit hosts
      command: "sh -c 'echo 127.0.1.1 $(hostname) >> /etc/hosts'"
      become: yes

    - name: download nginx
      unarchive:
        src: http://nginx.org/download/nginx-1.12.1.tar.gz
        dest: ~/
        remote_src: yes

    - name: download nginx-rtmp-module
      unarchive:
        src: https://github.com/arut/nginx-rtmp-module/archive/43f1e4209b7ee7b795595912943a8fdc37f2ea4a.zip
        dest: ~/
        remote_src: yes

    - name: build nginx with nginx-rtmp-module
      command: >
        bash -lc "cd /home/centos/nginx-1.12.1/
        && ./configure
        --sbin-path=/usr/sbin/nginx
        --conf-path=/etc/nginx/nginx.conf
        --error-log-path=/var/log/nginx/error.log
        --http-log-path=/var/log/nginx/access.log
        --pid-path=/var/run/nginx.pid
        --lock-path=/var/run/nginx.lock
        --prefix=/usr/local/nginx
        --user=nginx
        --group=nginx
        --with-http_ssl_module
        --with-http_realip_module
        --with-http_addition_module
        --with-http_sub_module
        --with-http_dav_module
        --with-http_flv_module
        --with-http_mp4_module
        --with-http_gzip_static_module
        --with-http_random_index_module
        --with-http_secure_link_module
        --with-http_stub_status_module
        --add-module=/home/centos/nginx-rtmp-module-43f1e4209b7ee7b795595912943a8fdc37f2ea4a
        && make
        && make install"
      become: yes

    - name: nginx setting
      copy: src=files/nginx/nginx.conf dest=/etc/nginx/nginx.conf
      become: yes

    - name: nginx group
      group:
        name: nginx
        state: present
      become: yes

    - name: add nginx user
      user:
        name: nginx
        state: present
      become: yes

    - name: make nginx user loginable
      command: usermod -s /bin/false nginx
      become: yes

    - name: make nginx service
      copy: src=files/nginx/nginx.service dest=/usr/lib/systemd/system/nginx.service
      become: yes

    - name: make nginx auto start up daemon && start nginx
      service:
        name: nginx
        state: started
        enabled: yes
      become: yes
